Azure/go-amqp

Makefile
README.md
azure-pipelines.yml
doc.go
example_test.go
fuzz.go
go.mod
go.sum
integration_test.go
local_test.go
sasl_test.go

Fixed references to new package path.
Removed dependencies on Azure SDK for now; this required disabling the
integration tests as they depend on it.
Added go.mod and go.sum files.
Added back content removed from README.md file.

Fixes for initial release

---

client.go
conn.go

This allows for larger messages to be transferred.
Values taken from the C# implementation.

Increase max frame and incoming window sizes

---

azure-pipelines.yml
fuzz.go

Added missing context parameter introduced in last commit.
Force Go modules mode and enabled gofuzz in tests.

Fix gofuzz

---

README.md

Context was missing as parameter.

docs: fix code sample

---

link.go

Use the message `DeliveryTag` as key in the unsettled map rather than the `DeliveryID`.
The `DeliveryID` is a monotously incremented ID for each message delivery. There is no rule as to where it should start though, and I'm not sure how it behaves on lost connection/session.
The `DeliveryTag` is a uuid generated by the sender on each delivery, so we're safer with edge cases.
This also happen to the C# implementation: https://github.com/Azure/azure-amqp/blob/e5cc469ec333904d18f1ec7cbc950a4cf463b6f1/src/AmqpLink.cs#L935
We can safely convert the `[]byte` to a string as it can't be nil. string is an immutable byte array internally, so that works as a substitute for the map key.

fix: use delivery tag as key in unsettled map

---

.github/CODEOWNERS
azure-pipelines.yml
client.go
error_pkgerrors.go
error_stdlib.go
fuzz.go
fuzz_test.go
go.mod
integration_test.go
local_test.go
log.go
log_debug.go
marshal_test.go
receiver_test.go
types.go

Removed some dead code.
Fixed minor linter issues.
Updated CI to latest versions of Go.

Misc clean-up

---

conn.go
decode.go
encode.go
fuzz_test.go
internal/buffer/buffer.go
link.go
marshal_test.go
sasl.go
sasl_test.go
sender.go
types.go
types_test.go

Export all methods on `Buffer`.  No functional changes.

Move buffer to internal package

---

conn.go

Fixes https://github.com/Azure/go-amqp/issues/16

Advertise half of our idle timeout threshold per spec

---

client.go
client_test.go
conn.go
link.go
link_options.go
link_test.go
receiver.go
receiver_test.go
sasl.go
sender.go
sender_test.go
session.go

To make it clear which parts are internal and which aren't.

Export conn and link public surface area

---

internal/encoding/types.go
receiver.go

Make delivery states strongly typed

---

conn.go
conn_test.go

Removed internal test hooks, replaced with per-conn dialer that uses an
internal config to set it for testing purposes.

Improve support for fake dialing

---

client_test.go
conn_test.go
link_test.go
session_test.go

There are a few that remain, these will be addressed separately.

Remove unnecessary sleeps from tests

---

link.go
sender.go
sender_test.go

Wrap disposition error in a DetachError when auto-detaching on
disposition error is enabled.

Add remaining link options tests

---

link.go
receiver_test.go

Closing a receiver that has pending messages in excess of the link
credit would hang due to blocking on writing to the Messages channel.
Select on the Messages and close channel to unblock Close().

Fix hang closing receiver when there are pending messages

---

client.go
conn.go

Add amqp+ssl scheme

---

conn_test.go

Extra tick during shut down would lead to panic, closing a channel that
was already closed.  Use a buffered channel instead.
Increase the idle timeout to further reduce the chance for extra ticks.

Fix bug in TestKeepAlives

---

client.go
conn.go
internal/log/log.go
internal/log/log_debug.go
link.go
receiver.go
sasl.go
session.go

Move debug logging implementation to internal package

---

azure-pipelines.yml

Cleaned up dependency installation.
Moved to latest version of golangci-lint.

Update CI to latest versions of Go

---

client.go
conn.go
internal/debug/debug.go
internal/debug/debug_debug.go
link.go
receiver.go
sasl.go
session.go

In preparation for other debug things.

Renamed package internal/log to internal/debug

---

client.go
conn.go
conn_test.go
helpers_test.go
internal/frames/frames.go
internal/shared/shared.go
internal/test/test.go
link.go
marshal_test.go
sasl.go
sasl_test.go
session.go

In preparation for some upcoming refactoring.
No functional/test changes.

Moved some internal content to the internal directory

---

conn.go
const.go
internal/frames/parsing.go
marshal_test.go
sasl_test.go

Fixed up const declarations for better docs.
No functional/test changes.

Cleaned up conn.go go a bit more

---

azure-pipelines.yml

Updated to latest two versions of Go.
Updated to latest golangci-lint.

Update to supported Ubuntu versions in CI

---

receiver.go
sender.go

Clean up var names from sender/receiver refactor

---

CHANGELOG.md

prepare for v0.18.0 release

---

azure-pipelines.yml

For is no longer required.
Pin to a version.

Update azure-amqp sources

---

helpers_test.go
link.go
link_test.go
receiver.go
receiver_test.go
sender.go

Added doc comment explaining its semantics.
No functional changes.

Renamed field linkCredit to availableCredit

---

CHANGELOG.md
const.go
link_test.go
receiver.go

Fix incorrect docs around receiving messages

---

CHANGELOG.md
benchmark_test.go
conn_test.go
example_test.go
fuzz_test.go
integration_test.go
receiver.go
receiver_test.go
sender.go
sender_test.go

To allow for future expansion.

Add option types for Send and Receive

---

CHANGELOG.md
example_test.go
fuzz_test.go
integration_test.go
link_options.go
receiver.go
receiver_test.go
session_test.go

This accurately reflects its intended purpose.

Renamed Credit to MaxCredit

---

conn_test.go
helpers_test.go
internal/fake/net_conn.go
link_test.go
receiver_test.go
sender_test.go
session_test.go

Rename mocks package to fake

---

azure-pipelines.yml
integration_test.go

Update to latest golangci-lint.

Add Go 1.20 to CI

---

creditor.go
helpers_test.go
link.go
link_test.go
receiver.go
receiver_test.go
sender.go

Fixed test bug.  No functional changes.

Further refinement of link flow control vars

---

CHANGELOG.md
message.go

Replaced with their aliased types.

Remove type aliases

---

CHANGELOG.md

Prep for v0.19.1 release

---

README.md
conn.go
example_test.go

Refine README.md

---

CHANGELOG.md

Prep for 1.0.0 release

---

azure-pipelines.yml

Updated golangci-lint to latest version.

Update CI with latest versions of Go

---

CHANGELOG.md

Prep for v1.0.2 release

---

CHANGELOG.md
integration_test.go
message.go
message_test.go

Fixes https://github.com/Azure/go-amqp/issues/332

Add Null type for sending an AMQP null

---

internal/buffer/buffer.go

Add doc comments for buffer type and methods

---

azure-pipelines.yml

Update to latest version of golangci-lint.

Update CI to latest two versions of Go

---

CHANGELOG.md

Prep v1.2.0 for release

---

CHANGELOG.md

Prep for v1.3.0 release

---

CHANGELOG.md

Prep for v1.4.0-beta.1 release

---

CHANGELOG.md
integration_test.go
link_test.go
receiver.go

Two small updates:
- Update changelog with our potential release date (next week)
- Update DrainCredit to take an options bag, for possible future expansion/control if we need it.

Add in DrainCreditOptions, and update changelog for release next week.
