Azure/go-amqp

client.go

The MQ broker I am using does not support durable subscriptions without an expiration, so I need to be able to set the timeout to something non-zero. The timeout parameter already exists internally; this PR is just allowing it to be configured from the client.

Expose setting the Timeout property of source and target from the client

---

client.go
client_test.go

Some servers are opinionated about the encoded type that they expect specific link properties to have. The existing int64 property option encodes the property value as a long/64-bit integer. This option allows 32-bit integers to be sent, which are needed for numeric values sent to some servers.

Add option to set int32 properties on links

---

client.go
example_test.go
types.go

This PR is one of a series across the following repos:
- https://github.com/Azure/azure-service-bus-go - https://github.com/Azure/azure-service-bus-go/pull/175
- https://github.com/Azure/azure-amqp-common-go - https://github.com/Azure/azure-amqp-common-go/pull/46
- https://github.com/Azure/go-amqp - https://github.com/Azure/go-amqp/pull/7
That aims to address the following issue: https://github.com/Azure/azure-service-bus-go/issues/173 which relates to the original issue in Dapr: https://github.com/Azure/azure-service-bus-go/issues/173
Please read the issues referenced above for further details, the TLDR is to add context to message disposition.

Add context to message disposition methods

---

client.go

When a message disposition is sent, it can return an error (for example when a the lock is lost before sending the disposition).
The current implementation does not bubble this error up to the receiver, and so the client code is not notified that the disposition failed.
This change extracts the error from the disposition reply frame, and pushes it back on the corresponding receiver's error channel (stored on the inflight map)
AMQP debug logs showing the error coming on the receiver side : 
```
21:36:26.085405 RX(Session): Disposition{
Role: Sender, First: 0, Last: <nil>, Settled: true, State: Rejected{ 
Error: *Error{
Condition: com.microsoft:message-lock-lost, 
Description: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. …
```

fix: push disposition error on corresponding receiver error channel

---

receiver.go
receiver_test.go

spec : http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#type-receiver-settle-mode
in mode first, the receiver must spontaneously settle all incoming transfers.
This was not implemented before because the receiver was not waiting for dispositions, and so the bug wasn't visible.

Settle message spontaneously on receive mode first

---

link.go
receiver.go
receiver_test.go
types.go

Only call done() if the message hasn't been settled.  This showed up
after recent changes to mode first to correctly settle messages.

Avoid double-closing message channel

---

types.go

This change supports the fix to this issue: https://github.com/Azure/azure-service-bus-go/issues/221.
The `associated-link-name` property is missing when calling `RenewLocks` function. Without it the Azure SB terminates the connection after the 10min idle timeout.

Add Message.GetLinkName() returning the associated link name

---

link.go
receiver_test.go

This should fix #33 by running `addUnsettled` only in ModeSecond, same as trackCompletion:
https://github.com/Azure/go-amqp/blob/51f7e70071303e8e3e3e867fc068dedeb2f31e44/receiver.go#L53-L55

Only track unsettled messages in ModeSecond

---

client.go
go.mod
link.go
receiver.go
receiver_test.go
sender.go
sender_test.go
session.go

As part of an investigation into an issue in Event Hubs I found a couple of cases that were problematic when attempting to do recovery.
First, if an error happens (and the sender is subsequently closed) that same error will get repeatedly returned by the sender. The error itself is actually a throttling error (and was relevant the first time it was returned) but after that we really should be indicating the link will _never_ work again because it has been closed.
The second is just exposing the link ID so it's simpler, from the outside, to tell one sender apart from another. As part of a separate change I want to make in Event Hubs I need to be able to see if the sender that I'm about to close/remove is actually the same one I started with (if it's not then I don't have to recover since …

Add some changes to make connection recovery easier for senders

---

client.go
link.go

This allows us (in Event Hubs) to choose whether we want to actually disconnect the link on disposition errors. There's a good performance optimization to be had if we can avoid that.
By default, we use the old logic, to remain compatible with previous go-amqp releases.

Allow the user of the link to determine if it should detach on disposition errors

---

client.go
session.go

At moderate concurrency, we could eat up the session window which was defaulted to a low value (100)
This caused a nasty bug to manifest. the window values are stored as uint.
it is decremented at each transfer. in some cases the uint would loop to intMax.
Once the window would have such a high value, the client stops sending Flow frames, because it thinks its window is huge.
eventually, no messages would get sent, because the remote peer and the local peer are out of sync, and no flow is sent across to reconciliate their state.
This PR fixes the window decrement by stopping it at 0 to prevent looping to int max.
- removes 2 places in the code where go-amqp was pre-emptively setting the outgoing window, probably as a workaround to the uint looping to max int. it now relies on the …

Fix remote outgoing window handling

---

sender.go

The AMQP broker should (on attaching) return the actual max message size for the link.
Both Azure Event Hubs and Azure Service Bus SDKs can use this to dynamically determine the maximum size allowed, rather than attempting to hard code it using constants for each tier.
This information was already being stored, so this PR just makes it so you can access that data from the outside.

Expose the max message size so we can use it when creating a batch

---

message.go
receiver.go
sender.go
sender_test.go

This PR adds `LinkName()` functions exposing associated link name.
The associated link name passed as a property to the management messages helps keep the session and link active.
This change supports implementation of https://github.com/Azure/azure-service-bus-go/issues/226

Access the associated link name

---

link.go

When a reject disposition comes back to us it doesn't have to have an error in it. 
We were propagating it when we did have an error, which was good, but we need to make sure we properly "erase" the type on the 'nil' when it's not.
Part of a fix for a bug found in Service Bus: https://github.com/Azure/azure-service-bus-go/issues/215

Don't set dispositionError to encoding.Error(nil)

---

link.go
link_test.go
manualCreditor.go
manualCreditor_test.go
receiver.go
session.go

Added inFlight.len method for safe reading of in-flight count.
Set the drained channel to nil once the drain is complete.
Don't read linkCredit from outside link type.

Fix some race conditions

---

benchmark_test.go
example_test.go
fuzz_test.go
integration_test.go
link.go
message.go
receiver.go
receiver_test.go

Moved methods from Message to Receiver.
Removed Receiver.HandleMessage.
Fixed auto-accept in ModeFirst.
Check for closed link during blocking Receive.

Move message disposition methods to Receiver

---

conn.go
integration_test.go
internal/frames/parsing.go
internal/mocks/connection.go
internal/mocks/net_conn.go
link.go
marshal_test.go
receiver_test.go

This includes a mock net.Conn and various helper funcs for creating mock
response frames.
Moved frame parsing out of conn.go and into frames package so that the
mock infrastructure can use it.
Fixed a bug in link uncovered by new unit tests.
Rewrote receiver tests using the new framework.

Add mocks package for unit testing

---

client.go
client_test.go
conn.go
conn_test.go
errors.go
internal/mocks/net_conn.go
link.go
link_test.go
receiver_test.go
sasl.go
session.go

Return nil *Client if Dial() fails.
Moved tests in client_test.go to link_test.go as they are link tests.
Moved DetachError from client.go to errors.go.
Cleaned up some ambiguous error strings.
Set default values for PerformOpen in mock connection.
Changed some Printf to debug.
Fixed a hang when deallocating a session whose mux isn't running.
Added various comments.

Add unit tests for client

---

receiver.go
receiver_test.go

This is useful for scenarios outlined in #71, where we have stopped adding in new credit (after a drain) and just want to make sure we're only reading in messages that have been cached internally and not waiting for additional messages that will never come, since we've drained all credit.
Fixes #71

Make it possible to only read cached messages only

---

receiver.go

This PR changes our logic to not early-exit `Receive()` if l.close is closed. This fixes a data race we're seeing in Service Bus.
There are two channels that track the state of a link:
- `l.Detached`, which gets closed after muxDetach() ultimately completes. This basically functions as a "mux is ended" signal.
- `l.close`, which gets closed immediately when you call link.Close()
Receive is intended to wait for the mux to exit. If it doesn't then it can't return any contextual error that might have been set by mux() or it's multiple friends (muxFlow, muxDetach).

Fixing a data race where the mux could unwind while we're simultaneously reading the last error

---

client.go
client_test.go
conn.go
errors.go
helpers_test.go
internal/mocks/net_conn.go
link.go
link_options.go
receiver_test.go
sender.go
sender_test.go
session.go
session_test.go

Fixed a bug where DetachError was lost on receipt.  This made
ErrLinkDetached unnecessary so it's been removed.
Removed link.Check as it's no longer required.
Clear in-fligt messages before declaring the mux as detached.
Documented a deadlock between conn and session with pending test.
Require role when calling mocks.PerformDisposition.
Added mocks.PerformDetach.
Added various code comments.

Add unit tests for Sender

---

client_test.go
conn_test.go
helpers_test.go
link_test.go
sender_test.go
session_test.go

Provide responder helpers to consolidate frame responders for tests
that don't require special/incorrect frame responses.

Consolidate some test responders

---

conn.go
session.go
session_test.go

Read and discard any errant frames send to the session when the mux is
unwinding.  This prevents the conn mux from being blocked which can lead
to a deadlock.

Fix deadlock between conn and session

---

client_test.go
conn_test.go
helpers_test.go
internal/mocks/net_conn.go
link.go
link_test.go
receiver.go
receiver_test.go
sender_test.go
session.go
session_test.go

Fixed an issue where malformed deliveries returned a different error
type from that which was used to close the link.
Fixed a potential deadlock during link.muxDetach.
Set Message.settled to true when confirmation of settlement is received.
Added support to mocks.NetConn for sending multi-frame transfers.
Made filter configurable in mocks.ReceiverAttach.
Added support for multi-message dispositions.

Add unit tests for Receiver

---

link.go
manualCreditor.go
manualCreditor_test.go

Unblock pending drain during link.muxDetach.
Exit manualCreditor.Drain if the link has been detached.

Fix hangs in manual credit management

---

azure-pipelines.yml
conn.go
helpers_test.go
receiver_test.go

The unhandled frame was causing some tests to fail due to the link
detaching.
Updated waitForLink() to handle a detached link which makes it clear why
the test would fail.

Eat keep-alive frames in receiver unit tests

---

internal/encoding/decode.go
internal/encoding/types.go
message.go
message_test.go

fixes #119
It seems that there is a bug when decoding maps with the type encoded as ULong instead of SmallULong.
I added a test to reproduce the issue and a fix in the affected code.
I didn't have a 0 length map to test it with, so I'm not sure about the returned size for the `TypeCodeUlong0` type, please check.
Thank you again for this library!

fix reading application properties with ULong type

---

message.go
message_test.go

Adding in AMQP sequence support.
This makes it so we can now encode and decode all the body types from the AMQP spec - data, value and now sequence. There can be multiple sequences encoded into a single body.
Fixes #94

Adding in AMQP sequence support.

---

link_test.go
manualCreditor.go
manualCreditor_test.go

Drain() was forwarding the error from the Detach frame. When that error is nil it's of type (*encoding/amqpError), which doesn't compare against error(nil) properly.
This just makes sure we translate it before returning it.

Fixing an issue where a drain would return a nil *amqp.Error, rather than error(nil)

---

internal/frames/frames.go

This is a change related to PR [#41](https://github.com/Azure/go-amqp/pull/41). 
Back when the change in PR #41 was made (July 15, 2021), there was a types.go in the root directory that needed a change in order to support SASL External.
On Sept 8, 2021, the types.go file was removed and it's SASL-related functionality was moved to internal/frames/frames.go.
On Sept 16, 2021, PR #41 was merged but the changes to types.go were lost.
This pull request is for the missed change that now needs to be in internal/frames/frames.go.

SASL External Fix

---

receiver.go

We were previously calling Accept() on messages when received in modeFirst. It turns out this isn't needed - the messages themselves are "spontaneously" settled, so no round-trip back to the service is required.
This helps us with another case - when we want to flush all the messages from the receivers' internal buffer after we've closed it (or it's become detached), which is impossible to do if we are also trying to do network IO.
Fixes #124

Remove unneeded disposition in modeFirst

---

client_test.go
conn.go
conn_test.go
errors.go
integration_test.go
internal/mocks/net_conn.go
receiver_test.go
sender_test.go

Errors reading from/writing to the underlying net.Conn were being
propagated to the sender/receiver APIs, making them hard to identify.
Now, when the connection is no longer functional, a ConnectionError
instance is returned.  If the connection died due to a read/write error,
the ConnectionError will contain this information.
Removed ErrConnClosed as it's too simplistic and can't capture the
reason why the connection was closed.

Return *ConnectionError when connection has faulted

---

link.go

It fixes `nil` panic for the `l.receiver`:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x6adca1]
goroutine 11352 [running]:
github.com/Azure/go-amqp.(*link).muxHandleFrame(0xc0001761e0, {0x7dbbe0, 0xc000402c80})
/home/tymon/go/pkg/mod/github.com/!azure/go-amqp@v0.17.4/link.go:682 +0x501
github.com/Azure/go-amqp.(*link).mux(0xc0001761e0)
/home/tymon/go/pkg/mod/github.com/!azure/go-amqp@v0.17.4/link.go:375 +0x1d3
created by github.com/Azure/go-amqp.attachLink
/home/tymon/go/pkg/mod/github.com/!azure/go-amqp@v0.17.4/link.go:256 +0x809
exit status 2
```

Fix link panic when l.receiver == nil

---

CHANGELOG.md
client.go
conn.go
errors.go
link_options.go
message.go
session.go
session_test.go

Fixed some stuttering type names.
Default constants are no longer exported.

Clean up public surface area

---

CHANGELOG.md
receiver.go
receiver_test.go

Moved all optional parameters to ModifyMessageOptions type.

Receiver.ModifyMessage takes an options struct

---

CHANGELOG.md
benchmark_test.go
example_test.go
fuzz_test.go
integration_test.go
internal/encoding/types.go
link.go
link_options.go
link_test.go
receiver.go
receiver_test.go
sender_test.go
session.go
session_test.go

Added SenderOptions and ReceiverOptions types which replicates the
previous functional options.
Options that are specific to senders/receivers have been moved to their
respective options types.
Added Ptr() methods to SenderSettleMode and ReceiverSettleMode to
simplify setting these optional values.

Replace varadic config for Sender and Receiver with struct config

---

receiver.go
receiver_test.go

Disposition of a message would hang if the link was closed prior to the settlement function being called.
The problem is that we don't do a link check to see if our link is valid anymore, which can lead to:
1. Receive message
2. Link is detached
3. Settle message
For message settlement all the traffic happens through the session and connection, not necessarily the link, which means that if the link is detached or dead we have a disposition that has a channel that we never close, resulting in a hang.
Fixes #126

Fixing disposition hanging if the link is closed

---

internal/mocks/net_conn.go
receiver_test.go
sender_test.go

Use a channel to communicate the fake write error.

Fix race condition in tests simulating write errors

---

CHANGELOG.md
link.go
manualCreditor.go
receiver_test.go

Peer can continue to send transfer frames until the detach request has
been acknowledged, so don't discard them.
Don't continuously send flow frames when a drain is requested.

Don't ignore transfer frames during link detach

---

CHANGELOG.md
session.go

Track the number of received transfer frames.  Once it's half or more of
the incoming window, send a flow frame to the peer to expand the window
and then reset the count.  This preserves the existing window behavior
without continuously sending flow frames until our peer sends one.
Increase window size to align with other implementations and also
resolve some issues uncovered during stress.

Don't flood peer with flow frames

---

azure-pipelines.yml
client.go
internal/frames/frames.go
link_options.go
manualCreditor.go
sasl_test.go

Update to latest golangci-lint for Go 1.19.

Update to latest two versions of Go

---

CHANGELOG.md
client.go
client_test.go
conn.go
session.go
session_test.go

Session objects are now managed via NewSession() and DeleteSession()
APIs on conn, no longer requiring mux to be "pumped".
Potential Session object leak due to expiring context has been fixed.
Fixes https://github.com/Azure/go-amqp/issues/164

Make Session allocation/deallocation deterministic

---

CHANGELOG.md
link.go
sender_test.go
session.go

Link handles are now managed via allocateHandle() and
deallocationHandle() APIs on Session, no longer requiring mux to be
"pumped".
Potential handle leak due to expiring context has been fixed.
Fixes https://github.com/Azure/go-amqp/issues/166

Make link allocation/deallocation deterministic

---

helpers_test.go
link.go
link_test.go
manualCreditor.go
manualCreditor_test.go
message.go
receiver.go
receiver_test.go
sender.go
sender_test.go
session.go

Split sending and receiving link functionality into their respective Sender and Receiver types.  The remaining content in link.go is what's common for both link types.
Each link type has their own mux and frame handlers as there are subtle differences between sending and receiving links.
The original implementations were cut/paste into their relevant files. Other than some local var renaming, there should be no functional changes.

Refactor link implementation

---

client.go
client_test.go
conn.go
link.go
receiver.go
sender.go
session.go

Move construction logic out of Client.NewSession and into Session.begin (this mimics the code flow for link attachment).
Merged Session.init into newSession.
Removed redundant *Session param from link.attach().

Refactor Session constructor

---

azure-pipelines.yml
link_test.go

Link refactoring introduced a regression in TestLinkFlowWithDrain. Removed reading from l.receiverReader as the mux reads it now.
Enable test corpus in CI.

Fix test bug

---

CHANGELOG.md
CONTRIBUTING.md
README.md
conn.go
conn_test.go
fuzz_test.go
go.mod
integration_test.go
internal/bitmap/bitmap_test.go
internal/debug/debug.go
internal/debug/debug_debug.go
internal/encoding/decode.go
internal/encoding/encode.go
internal/encoding/fuzz_test.go
internal/encoding/types.go
internal/frames/frames.go
internal/test/test.go
link.go
link_options.go
link_test.go
marshal_test.go
message.go
message_test.go
receiver.go
receiver_test.go
sasl_test.go
sender.go
session_test.go

Allows usage of any instead of interface{}.
Removed imports of ioutil and replaced with equivalent packages. Cleaned up README.md a little.
No functional/test changes.

Update Go version to 1.18

---

link_options.go
message.go
receiver.go
sender.go

Refactor from variadic config inadvertently removed this ability.  Added config options to sender and receiver for specifying peer durability.
Fixes https://github.com/Azure/go-amqp/issues/191

Enable configuration of durable subscriptions

---

CHANGELOG.md
link_options.go
link_test.go
receiver_test.go

Rename link filter constructors per guidelines.

---

CHANGELOG.md
conn.go
conn_test.go
errors.go
example_test.go
integration_test.go
link.go
manualCreditor.go
manualCreditor_test.go
receiver.go
receiver_test.go
sender.go
sender_test.go
session.go
session_test.go

The session and link sentinel error types have been removed. Added SessionError type which allows more descriptive errors. Fixed some error corner-cases to ensure they return DetachError. Removed spurious error text on peer-initiated ending of a session.
Fixes:
- https://github.com/Azure/go-amqp/issues/98
- https://github.com/Azure/go-amqp/issues/109
- https://github.com/Azure/go-amqp/issues/127

Refactor error types

---

link.go
receiver.go
sender.go
sender_test.go
session.go
session_test.go

Early exit in link.attach was closing l.rx on receiving of attach performative.  When the detach performative arrives, the session mux would panic attempting to send to a closed channel. Removed channel for "positive confirmation on transmission" as it's racy and doesn't actually work that way.

Fix panic due to sending on closed channel

---

CHANGELOG.md
conn.go
conn_test.go
fuzz_test.go
integration_test.go
internal/mocks/net_conn.go
internal/testconn/testconn.go
sender_test.go
session.go
session_test.go

conn.connReader() dispatches frames directly to sessions now.
Added conn.NextSession() and conn.DeleteSession() for deterministic
session management.
Channel numbers are now recycled immediately which prompted a fix for
TestSessionClose.
Fixed various tests to handle close frame (the error was being swallowed
before).
Tests that utilize testconn were silently failing due to a bug in
Conn.Read which has been fixed.
Fixes https://github.com/Azure/go-amqp/issues/164

Remove conn.mux

---

CHANGELOG.md
creditor.go
creditor_test.go
internal/frames/frames.go
link_options.go
link_test.go
receiver.go

Auto link flow control is now built on the creditor. Renamed some types to clarify their usage.
Removed double buffering of incoming frames for receiver.
Fixes https://github.com/Azure/go-amqp/issues/73

Consolidate auto and manual link flow control

---

CHANGELOG.md
conn.go

With the default value for `Conn.IdleTimeout` being set as `1 * time.Minute`, that results in `60000000000` or `1 * 60 * 1000 * 1000 * 1000 * time.Nanosecond`, as opposed to `60000.` Caused me a tiny headache when I tried setting it to actual millisecond values as I could not establish a connection.
- [-] Tests are included and/or updated for code changes.
- [-] MIT license headers are included in each file.

Clarify that Conn IdleTimeout is not in milliseconds

---

CHANGELOG.md
azure-pipelines.yml
conn.go
link.go
receiver.go
sender.go
session.go

If a session's mux terminates before connReader attempts to send it a frame, connReader will become blocked.
Renamed Session.err to follow pattern used in other places.
Inspired by https://github.com/Azure/go-amqp/issues/216

Fix potential deadlock in connReader

---

CHANGELOG.md
sender.go
sender_test.go
session.go

Assign delivery IDs to outgoing transfers from the session mux to ensure the IDs are in sequence.
Fixed an off-by-one error to ensure that the outgoing transfer ID aligns with the value sent by the flow frame.
Fixes
- https://github.com/Azure/go-amqp/issues/135
- https://github.com/Azure/go-amqp/issues/183

Ensure outgoing delivery IDs are sequential

---

CHANGELOG.md
integration_test.go
receiver.go
receiver_test.go

Receivers configured for ModeFirst weren't tracking unsettled messages. As a result, their session would send them more messages than their link credit would allow, causing the session mux to be blocked. With the session mux blocked, senders within the same session were unable to send messages.
Fixes https://github.com/Azure/go-amqp/issues/117

Fix potential deadlock between senders and receivers

---

CHANGELOG.md
integration_test.go
internal/frames/frames.go
link_test.go
sender.go
session.go

When a sender's peer is in mode second, the disposition confirmation must be sent through the session so that the in-flight disposition tracker can be closed.
Fixes https://github.com/Azure/go-amqp/issues/85

Enable at-most-once for senders

---

CHANGELOG.md
benchmark_test.go
conn.go
conn_test.go
example_test.go
fuzz_test.go
integration_test.go
link_test.go
receiver_test.go
sasl_test.go
sender_test.go
session_test.go

Removed ConnOptions.Timeout as it's no longer required.

Add context.Context param to Dial and NewConn

---

CHANGELOG.md
internal/frames/frames.go
session.go

Keep the session mux running until the acknowledging end performative has been received.
Added fmt.Stringer implementation to PerformEnd.

Don't discard incoming frames while closing a session

---

CHANGELOG.md
creditor.go
creditor_test.go
helpers_test.go
link.go
link_test.go
receiver.go
sender.go
session.go

Mostly this renamed internal fields to be consistent with the patterns established in Conn and Session.
Fixed a bug in Drain() that could return the wrong error.

Refactor link termination handling

---

link.go
receiver.go
receiver_test.go
sender.go

It's only used by Receiver to send an error when detaching due to an error condition.
Renamed muxDetach to muxClose.

Move detachError field to Receiver

---

CHANGELOG.md
link_options.go
receiver.go

Use the prefix Source instead of Sender as this matches the protocol terminology and aligns with the field names in SenderOptions.

Renamed fields in ReceiverOptions for configuring source

---

CHANGELOG.md
errors.go
example_test.go
integration_test.go
link.go
link_options.go
link_test.go
receiver.go
receiver_test.go
sender.go
sender_test.go

Detach has a specific meaning in AMQP and since we don't support link detach/reattach the error type name is misleading. Cleaned up any misused detach verbage.
Fixes https://github.com/Azure/go-amqp/issues/224

Rename DetachError to LinkError

---

conn_test.go
helpers_test.go
internal/frames/frames.go
internal/frames/parsing.go
internal/mocks/net_conn.go
link_test.go
marshal_test.go
receiver_test.go
sender_test.go
session_test.go

Added fmt.Stringer support.
Removed duplicate definition from mocks package.

Make frame type a typed constant

---

CHANGELOG.md
receiver.go

There's a small window where messages might arrive and the link being closed before selecting on these conditions.  Drain any messages that might have arrived.
Fixes https://github.com/Azure/go-amqp/issues/125

Drain prefetched messages when Receiver is closed

---

CHANGELOG.md
link.go
receiver.go
receiver_debug.go
receiver_prod.go
session.go

Select on r.l.close in muxReceive instead of r.l.done.  The latter is only closed when the mux exits, and since muxReceive is called from the mux, this case will never trigger.
Add a debug build for selecting on r.messages that will panic if it's full.  This indicates a flow control bug.

Fix potential hang when closing a receiver

---

CHANGELOG.md
conn.go
link.go
receiver.go
receiver_debug.go
receiver_prod.go
sasl.go
sender.go
session.go

Centralized logging of incoming and outgoing frames at Conn and removed all redundant entries.
Log transfering of frames across mux at DEBUG_LEVEL 2. Frame entries now include the full frames.Frame info.
Fixes https://github.com/Azure/go-amqp/issues/187

Clean up debug log entries

---

CHANGELOG.md
creditor.go
receiver.go

This ensures that when the mux wakes up it will see the bit is set.

Wake up receiver mux after setting the drain bit

---

CHANGELOG.md
conn.go
session.go

Changed Session.rx to frames.FrameBody to remove extra level of indirection and passing data that isn't required.

Document default values for incoming and outgoing windows

---

creditor.go
helpers_test.go
link.go
link_test.go
receiver.go
receiver_test.go
sender.go

Moved to their respective types.  No functional changes.

Separate link credit variables for sender and receiver

---

azure-pipelines.yml

All Windows and Linux pipelines should use 1ES pools by default, unless they need to run in the DevOps Pool for a specific reason.

Use 1ES pool

---

benchmarks_test.go
helpers_test.go
marshal_test.go

Includes measurments for sending, receiving, and settling messages. Bumped up test session window to avoid flow control. Fixed a panic in the unmarshalling benchmark.

Added some additional benchmarks

---

CHANGELOG.md
creditor.go
creditor_test.go
example_test.go
fuzz_test.go
integration_test.go
link_options.go
link_test.go
message.go
receiver.go
receiver_test.go
session.go
session_test.go

This exposed an implementation detail of how Receivers worked.  With the removal of the Message channel, this is no longer required and never really made sense anyways.
The MaxCredit and ManualCredits options have been consolidated into a single Credit option.  This is used to set the total credit for a Receiver in auto-flow mode, or to disable auto-flow. Disposition batching needed some slight refactoring.  Now you can directly specify the batch size instead of it being tied to link credit.
Received messages that are sender-settled now correctly count towards a Receiver's credit and must be settled to reclaim it.
Fixes
- https://github.com/Azure/go-amqp/issues/217
- https://github.com/Azure/go-amqp/issues/240
- https://github.com/Azure/go-amqp/issues/249

Remove concept of "max credit" from Receivers

---

CHANGELOG.md
link_test.go
receiver.go

There's lack of uniformity on handling of drain across brokers, leading to flakey behavior.
Fixes https://github.com/Azure/go-amqp/issues/255

Remove DrainCredit API

---

CHANGELOG.md
conn.go
errors.go
link.go
link_test.go
receiver.go
sender.go
sender_test.go
session.go

The rx channel in Session and link has been replaced with a queue.  This
ensures that parents enqueueing frames to their children is always a non
blocking operation and removes the need to "pump the mux".
Consolidated some link creation code into newLink().
Links echoing a flow frame now correctly include session info.
Reverted workaround for sending disposition frames from senders as we
can now send directly from muxHandleFrame.

Replace incoming frame channels with queues

---

CHANGELOG.md
conn_test.go
link.go
receiver.go
sender.go
session.go

The values weren't actually honored which is ok per spec, so remove them from the public surface area.
Cleaned up handling of sender link credit.  Since we don't use availableCredit, it's been removed.
Fixes https://github.com/Azure/go-amqp/issues/83

Remove configuration of session window

---

CHANGELOG.md
integration_test.go
receiver.go

Reclaim credit for sender-settled messages when Prefetch or Receive are called.  This removes the need to explicitly settle the message.

Improve handling of sender-settled messages

---

CHANGELOG.md
integration_test.go
session.go

This is against the spec and results in the peer terminating the connection.  Just ignore any outgoing frames.

Disable Session sending frames after end performative

---

conn_test.go
session.go
session_test.go

Per spec section 2.8.17, the session must be terminated.
Fixes https://github.com/Azure/go-amqp/issues/182

Don't swallow unrecognized link handles

---

CHANGELOG.md
conn.go
conn_test.go
creditor.go
errors.go
link.go
link_test.go
receiver.go
receiver_test.go
sender.go
sender_test.go
session.go
session_test.go

Document the potential for connection errors.
This required refactoring the link closing code.  It now follows the
same pattern as Session.

Clean up state on context timeout/cancellation

---

CHANGELOG.md
link_options.go
link_test.go
sender.go
sender_test.go

This is not required per spec and there is no good reason for doing so.

Don't close Sender when peer rejects message

---

CHANGELOG.md
message.go
sender.go
sender_test.go

It's purely a client side value and is not part of the message proper. Send now returns an error if the setting conflicts with the Sender.
Partially fixes https://github.com/Azure/go-amqp/issues/215

Move per-message presettlement setting to SendOptions

---

CHANGELOG.md
conn_test.go
link.go
link_test.go
receiver.go
sender.go
sender_test.go
session.go
session_test.go

Terminate a session/link on receiving an unexpected frame. The change uncovered a race introduced in #223 where it's possible to send an *Error to a closed s.close causing a panic.
Fixes https://github.com/Azure/go-amqp/issues/81

Don't swallow unexpected frames

---

CHANGELOG.md
azure-pipelines.yml
helpers_test.go
internal/test/test.go
link_test.go
receiver.go
receiver_test.go
sender.go
session.go

Added some mux test hooks and supporting test infrastructure.
Fixes https://github.com/Azure/go-amqp/issues/169

Clean up tests that trigger the race detector

---

CHANGELOG.md
message.go
receiver.go

The data isn't germane to the Message and should be tracked externally as required.

Remove method Message.LinkName

---

CHANGELOG.md
link.go
receiver.go
receiver_test.go
sender.go
sender_test.go
session.go
session_test.go

If Close() exits due to cancellation/timeout and the mux is still running, subsequent calls to Close() will read from doneErr which will race with the mux.
Record closing state while synchronizing with the mux and cache the value so subsequent calls return the same value.
Example: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2668077&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=bd05475d-acb5-5619-3ccb-c46842dbc997

Fix race on Session/Sender/Receiver Close

---

CHANGELOG.md
conn.go
conn_test.go
integration_test.go
sasl.go

Previously they only honored a deadline, now they handle both. TLS dialer now calls DialContext().

Honor context cancellation in Dial and NewConn

---

CHANGELOG.md
conn.go
fuzz_test.go

Bumped up context timeout in TestFuzzConnCrashers.  This is unrelated to the race change.  Some iterations of the test starting failing with a context.DeadlineExceeded error.

Fix potential race in Conn.Close()

---

CHANGELOG.md
conn.go
link.go
receiver.go
sasl.go
sender.go
session.go

Include address of Conn/Session/Sender/Receiver when writing log entries.  This helps when a process contains multiple instances. Include the link name in the error string when a link is forcibly closed.
Include the channel number in the error string when a session is forcibly closed.
Add log entries when session/link is forcibly closed. Add log entry for muxing from Session to Conn.

Improved logging diagnostics

---

benchmarks_test.go
conn_test.go
helpers_test.go
internal/fake/net_conn.go
link_test.go
receiver_test.go
sender_test.go
session_test.go

The fakes used the same, or hard-coded, values for the local and remote channels which prevented writing certain kinds of tests.
Test-only change.

fakes: distinguish between local and remote channels

---

CHANGELOG.md
link.go
receiver.go
receiver_test.go
sender.go
session.go

Session mux no longer consumes frames once the end performative has been sent.  Instead, added channel endSent that links can select on. Added method link.txFrame for proper muxing of frames to session. Receivers send disposition frames through the mux to properly sync with the receiver being closed.
Senders disable the outgoing transfers channel once close has started.
Fixes https://github.com/Azure/go-amqp/issues/278

Sending frames synchronizes with mux

---

CHANGELOG.md
conn.go
conn_test.go
integration_test.go
link.go
link_test.go
receiver.go
receiver_test.go
sender.go
sender_test.go
session.go
session_test.go

If a context expires or is cancelled during session/link creation while waiting for the ack, add the instance to a slice for later cleanup. Removed force-closing of sessions/links.
Exhausting available session channels will return a *ConnError and close the Conn.
Exhausting available link handles will return a *SessionError and close the Session.
Fixes https://github.com/Azure/go-amqp/issues/277

Robust handling of context expiration/cancellation

---

CHANGELOG.md
receiver.go
receiver_test.go

For receivers in mode second, handle clean-up of in-flight messages from the mux instead of the disposition call.  This ensures that the link credit is reclaimed if the disposition API is cancelled or times out waiting for the disposition acknowledgement.

Don't leak message settlement on context cancel/timeout

---

CHANGELOG.md
conn.go
helpers_test.go
internal/frames/frames.go
link.go
link_test.go
receiver.go
sasl.go
sender.go
sender_test.go
session.go

Added Conn.WriteDeadline to control the write deadline when writing to net.Conn.  The default value is 30 seconds.  This can be overridden by APIs that take a context and the context has a deadline/timeout. For APIs that directly send frames, wait for the frame to be written to the underlying net.Conn before considering the write a success.
Fixes https://github.com/Azure/go-amqp/issues/280

Make writes deterministic

---

CHANGELOG.md
conn.go
conn_test.go
helpers_test.go
integration_test.go
internal/fake/net_conn.go
receiver.go
receiver_test.go
sender.go
sender_test.go
session.go

Serialize the responses to write so that they show up in their specified order. This was responsible for some spurious test failures. Consolidate creation of senders and receivers with test hooks. Make sending and receiving of frames log level 0 to get the minimum amount of logging that can be useful.
Fixes https://github.com/Azure/go-amqp/issues/300

Fix non-determinism in fake NetConn.Write

---

conn.go
conn_test.go
internal/fake/net_conn.go

Related to https://github.com/Azure/go-amqp/issues/170 which was fixed in https://github.com/Azure/go-amqp/pull/273

Add unit test to verify conn is closed when start fails

---

CHANGELOG.md
conn.go
link.go
receiver.go
sender.go
sender_test.go
session.go

There were two observers of env.Sent, the session mux and the sender. If the sender was the first to read from the channel, this would cause the session mux to be blocked.
In order to support multiple observers, the channels must be treated as semaphores which are signaled when closed.
Don't terminate a session's mux if a transfer wasn't sent due to context cancellation/timeout (this is not terminal).

Fix potential hang in Sender.Send()

---

CHANGELOG.md
sender.go
sender_test.go

When a transfer fails to be sent due to context cancellation/timeout, roll back the updates to delivery count and link credit.
Fixes https://github.com/Azure/go-amqp/issues/298

Roll back sender's delivery count and link credit

---

CHANGELOG.md
message.go
receiver.go

It's not prevented at present, but can cause a memory leak due to entries never being removed from the unsettledMessages map. When a received message isn't settled, associate its receiver with the message. The settlement APIs will direct to the associated receiver.

Allow cross receiver message settlement

---

CHANGELOG.md
link_test.go
receiver.go

The unsettled map is currently used as a count for diagnostic purposes only, so it's safe to convert it to a count.
Fixes https://github.com/Azure/go-amqp/issues/317

Track receiver's unsettled messages as a count

---

conn_test.go
internal/fake/net_conn.go

Added a unit test to cover the fix made in a819335.

Fake can split up response frames into chunks

---

benchmarks_test.go
conn_test.go
internal/fake/net_conn.go
link_test.go
receiver_test.go
sender_test.go
session_test.go

Includes ChunkSize to set a default for the fake.NetConn.

Add fake.NetConnOptions

---

CHANGELOG.md
errors.go
errors_test.go

In the majority of common use cases, the LinkError, ConnError and SessionError will contain an amqp.Error. It's simpler, for callers, if they can simply check errors.As(&amqp.Error) so they can write general error handling, rather than having to check the envelope type each time.

Allow for errors.As() to see the underlying AMQP error

---

CHANGELOG.md
conn.go

If the provided context is canceled/expires after connReader and connWriter are started, the resultant *Conn will be nil causing their goroutines to be leaked.

Fix race in Conn.start

---

CHANGELOG.md
conn.go
conn_test.go
link.go
receiver.go
receiver_test.go
sender.go
sender_test.go
session.go
session_test.go

Exposes peer properties for the respective performatives.
Fixes:
- https://github.com/Azure/go-amqp/issues/32
- https://github.com/Azure/go-amqp/issues/220

Add Properties methods

---

CHANGELOG.md
message.go
message_test.go

This allows sending an explicit false.
Fixes https://github.com/Azure/go-amqp/issues/330

Always encode MessageHeader.Durable field

---

CHANGELOG.md
conn.go
conn_test.go
errors.go
example_test.go

Signals when a connection has been closed and any associated error.

Add Done and Err methods to Conn

---

CHANGELOG.md
message.go

This PR make the encoding.Symbol type exposed as a public type `Symbol`.
We recently [implemented AMQP Filter Expressions](https://github.com/rabbitmq/rabbitmq-server/pull/12415) in RabbitMQ. If the client wants to filter based on a property, the property name should be encoded as a `Symbol`, therefore the client needs to be able to use a `map[amqp.Symbol]any` in ` amqp.NewLinkFilter`
See https://github.com/rabbitmq/omq/blob/filter-properties/pkg/amqp10_client/consumer.go#L273-L279 for an example that works using a branch of go-amqp.
Thanks,

Expose the Symbol type

---

internal/encoding/exported_types.go
internal/encoding/types.go

This makes it clear which internal types are publicly exported.
No functional changes.

Move exported internal types to their own file

---

CHANGELOG.md
integration_test.go
link_test.go
receiver.go

We originally removed drain for https://github.com/Azure/go-amqp/issues/255, but it's functionality we do need for Service Bus again, for an upcoming fix.
The original reason for removal was about compliance to the spec, however, I think the broker in question (ActiveMQ) is actually _out_ of spec.
Here's the relevant section, from the FLOW frame documentation. I've added some line breaks, to make it more clear what each piece is:
> The drain flag indicates how the sender SHOULD behave when insufficient messages are available to consume the current link-credit. If set, the sender will:
>
> (after sending all available messages) 
>
> advance the delivery-count as much as possible, consuming all link-credit, 
>
> and send the flow state to the receiver. 
This is what the current …

Reviving DrainCredit(), adding back into Receiver
